version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12

    working_directory: ~/styled-miniresetcss

    steps:
      - checkout

      - run:
          name: install-yarn-and-upgrade-npm
          command: "sudo npm install -g yarn@latest npm@latest"

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build

  publish:
    docker:
      - image: circleci/node:10.12

    working_directory: ~/styled-miniresetcss
    steps:
      - checkout
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org:_authToken=$NPM_TOKEN
            npm publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - publish:
          requires:
            - build
